# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glide < Formula
  desc "One API, Every Telecom Network"
  homepage "https://clearx.io"
  version "0.1.0"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Darwin_x86_64.tar.gz"
      sha256 "5798ad94c66321e6d4ceb4d8753648cf41a73bdb60e771806648ebeca205f3c7"

      def install
        bin.install "glide"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Darwin_arm64.tar.gz"
      sha256 "31c5ff68840e00b39741e748dcc57e600640ac3d91a8a3a17209bcdec168a37c"

      def install
        bin.install "glide"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Linux_x86_64.tar.gz"
      sha256 "d22db55529202b5b226c0889d671e6cb5316618a9d9ae607e7f94478fcd7fe91"

      def install
        bin.install "glide"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Linux_arm64.tar.gz"
      sha256 "89583a769556b92e1dbf19f6f0951e0db9f33c73b11ef5cc436b8e3df6423233"

      def install
        bin.install "glide"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
  end

  test do
    system "#{bin}/glide -v"
  end
end
