# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glide < Formula
  desc "One API, Every Telecom Network"
  homepage "https://clearx.io"
  version "0.1.0"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Darwin_x86_64.tar.gz"
      sha256 "6a12672ba6eb6724175855b173e5eada771d428f91e22d35b942dd207adf1c8a"

      def install
        bin.install "onboarding-cli"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Darwin_arm64.tar.gz"
      sha256 "ac37cbd15c9d59c531cc09bb0f10c2de53443d48dff1101187bc6479d5a80fa1"

      def install
        bin.install "onboarding-cli"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Linux_x86_64.tar.gz"
      sha256 "d8d9ee1c84d5d2bab7d000e60060566621749f114e0a8966f7ef064ef7abc662"

      def install
        bin.install "onboarding-cli"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Linux_arm64.tar.gz"
      sha256 "716484f94aec2c26125ebbbbad02feabf21f88284448a83f0e050a3125167edd"

      def install
        bin.install "onboarding-cli"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
  end

  test do
    system "#{bin}/glide -v"
  end
end
