# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OnboardingCli < Formula
  desc "One API, Every Telecom Network"
  homepage "https://clearx.io"
  version "0.1.0"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Darwin_x86_64.tar.gz"
      sha256 "f96d8e30a17455078f766be61273d2ecda9bf3eed9098540babf44bfb73aed36"

      def install
        bin.install "onboarding-cli"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Darwin_arm64.tar.gz"
      sha256 "5f57098e67c40b2911fb2a4cd4edc4b48e63906bd932b46c0360ac9d1be69554"

      def install
        bin.install "onboarding-cli"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Linux_x86_64.tar.gz"
      sha256 "23ef0bdaf24ded553624a938566c9faa42831c0b89b249165a808f10c2325984"

      def install
        bin.install "onboarding-cli"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ClearBlockchain/onboarding-cli/releases/download/v0.1.0/onboarding-cli_Linux_arm64.tar.gz"
      sha256 "2662941aceb66392c2d36cf64c6219b92618c601ee1e574432968f5ac3e5221e"

      def install
        bin.install "onboarding-cli"
        bash_completion.install "completions/glide.bash" => "glide"
        zsh_completion.install "completions/glide.zsh" => "_glide"
        fish_completion.install "completions/glide.fish"
      end
    end
  end

  test do
    system "#{bin}/glide -v"
  end
end
